# Form implementation generated from reading ui file 'ranobeView.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_ranobeView(object):
    def setupUi(self, ranobeView):
        ranobeView.setObjectName("ranobeView")
        ranobeView.resize(800, 560)
        ranobeView.setMinimumSize(QtCore.QSize(800, 560))
        ranobeView.setMaximumSize(QtCore.QSize(800, 560))
        ranobeView.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons8-my-melody-480.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ranobeView.setWindowIcon(icon)
        ranobeView.setStyleSheet("#ranobeView{\n"
"    background:  #272727;\n"
"}\n"
"")
        self.volumesList = QtWidgets.QListWidget(ranobeView)
        self.volumesList.setGeometry(QtCore.QRect(10, 300, 500, 250))
        self.volumesList.setStyleSheet("#volumesList{\n"
"    background: #48494a;\n"
"}")
        self.volumesList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.volumesList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.volumesList.setAutoScroll(False)
        self.volumesList.setObjectName("volumesList")
        self.ranobeName = QtWidgets.QLabel(ranobeView)
        self.ranobeName.setGeometry(QtCore.QRect(10, 20, 500, 50))
        self.ranobeName.setStyleSheet("#ranobeName{\n"
"font-size: 22px;\n"
"font-family: sans-serif;\n"
"color: #ffffff;\n"
"}")
        self.ranobeName.setText("")
        self.ranobeName.setObjectName("ranobeName")
        self.ranobeDescription = QtWidgets.QLabel(ranobeView)
        self.ranobeDescription.setGeometry(QtCore.QRect(10, 90, 500, 200))
        self.ranobeDescription.setStyleSheet("#ranobeName{\n"
"font-size: 14px;\n"
"font-family: sans-serif;\n"
"color: #ffffff;\n"
"}")
        self.ranobeDescription.setText("")
        self.ranobeDescription.setObjectName("ranobeDescription")
        self.ranobeCover = QtWidgets.QLabel(ranobeView)
        self.ranobeCover.setGeometry(QtCore.QRect(530, 20, 240, 341))
        self.ranobeCover.setStyleSheet("#MainWindow{\n"
"    background:  #272727;\n"
"}\n"
"")
        self.ranobeCover.setText("")
        self.ranobeCover.setObjectName("ranobeCover")
        self.parseRanobe = QtWidgets.QPushButton(ranobeView)
        self.parseRanobe.setGeometry(QtCore.QRect(530, 380, 240, 75))
        self.parseRanobe.setStyleSheet("#parseRanobe{\n"
"    background-color: #000000;\n"
"    font-family: monospace;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"#parseRanobe:hover{\n"
"    background-color: #666;\n"
"    color: #272727;\n"
"}\n"
"\n"
"")
        self.parseRanobe.setObjectName("parseRanobe")
        self.loadRanobe = QtWidgets.QPushButton(ranobeView)
        self.loadRanobe.setGeometry(QtCore.QRect(530, 455, 240, 75))
        self.loadRanobe.setStyleSheet("#loadRanobe{\n"
"    background-color: #000000;\n"
"    font-family: monospace;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"#loadRanobe:hover{\n"
"    background-color: #666;\n"
"    color: #272727;\n"
"}\n"
"\n"
"")
        self.loadRanobe.setObjectName("loadRanobe")

        self.retranslateUi(ranobeView)
        QtCore.QMetaObject.connectSlotsByName(ranobeView)

    def retranslateUi(self, ranobeView):
        _translate = QtCore.QCoreApplication.translate
        ranobeView.setWindowTitle(_translate("ranobeView", "RenobeView"))
        self.parseRanobe.setText(_translate("ranobeView", "Save to File"))
        self.loadRanobe.setText(_translate("ranobeView", "Seve to Phone"))

